# Generated by Django 4.2.15 on 2025-08-27 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("RPG", "RPG"),
                            ("FPS", "FPS"),
                            ("Metroidvania", "Metroidvania"),
                            ("Visual Novel", "Visual Novel"),
                            ("Strategy", "Strategy"),
                            ("Puzzle", "Puzzle"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ambiance", models.CharField(max_length=120)),
                ("keywords", models.CharField(blank=True, max_length=200)),
                ("references", models.CharField(blank=True, max_length=200)),
                ("universe_text", models.TextField(blank=True)),
                ("story_act1", models.TextField(blank=True)),
                ("story_act2", models.TextField(blank=True)),
                ("story_act3", models.TextField(blank=True)),
                ("story_twist", models.TextField(blank=True)),
                ("characters", models.JSONField(blank=True, default=list)),
                ("locations", models.JSONField(blank=True, default=list)),
                (
                    "character_image",
                    models.ImageField(blank=True, null=True, upload_to="characters/"),
                ),
                (
                    "environment_image",
                    models.ImageField(blank=True, null=True, upload_to="environments/"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="games.gameproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game")},
            },
        ),
    ]
