# Generated by Django 4.2.15 on 2025-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameproject',
            name='concept_images',
            field=models.JSONField(blank=True, default=list, help_text='URLs des images concept uploadées', verbose_name='Images concept'),
        ),
        migrations.AddField(
            model_name='gameproject',
            name='use_user_images',
            field=models.BooleanField(default=False, help_text='Cochez pour utiliser vos images plutôt que celles générées par IA', verbose_name='Utiliser mes images'),
        ),
        migrations.AddField(
            model_name='gameproject',
            name='user_character_image',
            field=models.ImageField(blank=True, help_text='Uploadez votre propre image de personnage', null=True, upload_to='user_uploads/characters/', verbose_name='Image personnage (upload)'),
        ),
        migrations.AddField(
            model_name='gameproject',
            name='user_environment_image',
            field=models.ImageField(blank=True, help_text="Uploadez votre propre image d'environnement", null=True, upload_to='user_uploads/environments/', verbose_name='Image environnement (upload)'),
        ),
    ]
