# Generated by Django 4.2.15 on 2025-08-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameproject_concept_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameproject',
            name='concept_images',
        ),
        migrations.RemoveField(
            model_name='gameproject',
            name='use_user_images',
        ),
        migrations.RemoveField(
            model_name='gameproject',
            name='user_character_image',
        ),
        migrations.RemoveField(
            model_name='gameproject',
            name='user_environment_image',
        ),
    ]
